using System;

namespace DAIS.ORM.Framework
{
    [AttributeUsage(AttributeTargets.Property)]
    public class IgnoreAttribute : Attribute
    {
    }

    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Interface)]
    public class TableNameAttribute : Attribute
    {
        public string Name { get; }

        public TableNameAttribute(string name)
        {
            Name = name;
        }
    }

    public enum ColumnType
    {
        Normal,
        PrimaryKey,
        ForeignKey,
    }

    [AttributeUsage(AttributeTargets.Property)]
    public class ColumnAttribute : Attribute
    {
        public string Name { get; }
        public ColumnType Type { get; }
        public bool AutoGenerated { get; set; }
        public bool DeleteIndicator { get; set; }

        public ColumnAttribute(string name, ColumnType type = ColumnType.Normal)
        {
            Name = name;
            Type = type;
            AutoGenerated = false;
            DeleteIndicator = false;
        }
    }
}
